# Generated by Django 5.2.6 on 2025-09-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('MEETING', 'Meeting'), ('1ST_APPOINTMENT', '1st Appointment'), ('PRESENTATION', 'Presentation'), ('EVENT', 'Event')], max_length=20)),
                ('recurrence_rule', models.CharField(choices=[('NONE', 'Never'), ('DAILY', 'Daily'), ('WORKDAYS', 'Every Workday (Mon–Fri)'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly')], default='NONE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('meeting_type', models.CharField(blank=True, choices=[('MORNING', 'Morning Meeting'), ('LEADERS', 'Leaders Meeting'), ('CLIENT', 'Client Meeting'), ('OWNER', 'Owner Meeting'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('host', models.CharField(blank=True, choices=[('ROBERT_MILLER', 'Robert Miller'), ('STIG_MILLER', 'Stig Miller'), ('TRACY_PEW', 'Tracy Pew'), ('KLAUS_NOMI', 'Klaus Nomi'), ('ROSE_MCDOWALL', 'Rose McDowall')], max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendar_app.event')),
            ],
        ),
    ]
